import os

ITSM_SERVICENOW_URL = os.environ["ITSM_SERVICENOW_URL"]
ITSM_SERVICENOW_API_TOKEN = os.environ.get("ITSM_SERVICENOW_API_TOKEN")

ITSM_SERVICENOW_API_USER = os.environ.get("ITSM_SERVICENOW_API_USER")
ITSM_SERVICENOW_API_PASSWORD = os.environ.get("ITSM_SERVICENOW_API_PASSWORD")
